// <auto-generated />
using System;
using AplicacionEstudiantil.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicacionEstudiantil.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Actividades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<string>("Trabajos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Videos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Perfil");
                });

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasBaseType("AplicacionEstudiantil.App.Dominio.Entidades.Perfil");

                    b.Property<string>("Grado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MateriaId")
                        .HasColumnType("int");

                    b.HasIndex("MateriaId");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Profesor", b =>
                {
                    b.HasBaseType("AplicacionEstudiantil.App.Dominio.Entidades.Perfil");

                    b.Property<string>("GrupoAcademico")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Materia", b =>
                {
                    b.HasOne("AplicacionEstudiantil.App.Dominio.Entidades.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorId");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AplicacionEstudiantil.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasOne("AplicacionEstudiantil.App.Dominio.Entidades.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId");

                    b.Navigation("Materia");
                });
#pragma warning restore 612, 618
        }
    }
}
